af_gang_mail/urls.py
"""URLs."""

from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
from django.contrib.flatpages.views import flatpage
from django.urls import include, path, re_path

from af_gang_mail import views

urlpatterns = [
    path("in-case-of-emergency/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("su/", include("django_su.urls")),
    path(
        "__edit__/<pk>/",
        permission_required("flatblocks.change_flatblock")(views.edit_flatblock),
        name="edit-flatblock",
    ),
    path(
        "update-name-and-address/",
        views.UpdateNameAndAddress.as_view(),
        name="update-name-and-address",
    ),
    path("select-exchanges/", views.SelectExchanges.as_view(), name="select-exchanges"),
    path("create-exchange/", views.CreateExchange.as_view(), name="create-exchange"),
    path(
        "manage-exchanges/<slug:slug>/edit/",
        views.UpdateExchange.as_view(),
        name="update-exchange",
    ),
    path(
        "manage-exchanges/<slug:slug>/delete/",
        views.DeleteExchange.as_view(),
        name="delete-exchange",
    ),
    path(
        "manage-exchanges/<slug:slug>/draw/",
        views.DrawExchange.as_view(),
        name="draw-exchange",
    ),
    path(
        "manage-exchanges/<slug:slug>/delete-draws/",
        views.DeleteDrawsForExchange.as_view(),
        name="delete-draws-for-exchange",
    ),
    path(
        "manage-exchanges/draws/<int:pk>/", views.ViewDraw.as_view(), name="view-draw"
    ),
    path(
        "manage-exchanges/<slug:slug>/",
        views.ViewExchange.as_view(),
        name="view-exchange",
    ),
    path("manage-exchanges/", views.ManageExchanges.as_view(), name="manage-exchanges"),
    path("create-flatpage/", views.CreateFlatPage.as_view(), name="create-flatpage"),
    path(
        "manage-flatpages/<int:pk>/edit/",
        views.UpdateFlatPage.as_view(),
        name="update-flatpage",
    ),
    path("manage-flatpages/", views.ManageFlatPages.as_view(), name="manage-flatpages"),
    path("style-gallery/", views.StyleGallery.as_view(), name="style-gallery"),
    path("page-index/", views.PageIndex.as_view(), name="page-index"),
    path("home/", views.Home.as_view(), name="home"),
    path(
        "welcome/name-and-address/",
        views.SignUpStepOne.as_view(),
        name="sign-up-step-one",
    ),
    path("welcome/exchanges/", views.SignUpStepTwo.as_view(), name="sign-up-step-two"),
    path("resend-verification/", views.resend_verification, name="resend-verification"),
    path("tz_detect/", include("tz_detect.urls")),
    path(
        "exchange/<slug:slug>/confirm/",
        views.ConfirmParticipation.as_view(),
        name="confirm_participation",
    ),
    path("exchange/<slug:slug>/sent/", views.MailSent.as_view(), name="draw-sent"),
    path(
        "exchange/<slug:slug>/received/",
        views.MailReceived.as_view(),
        name="draw-received",
    ),
    path("exchange/<slug:slug>/", views.Draw.as_view(), name="draw"),
    path("statto/", views.Statto.as_view(), name="statto"),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("contact/", include("contact_form.urls")),
    re_path(r"^(?P<url>.*/)$", flatpage),
    path("", views.Landing.as_view(), name="landing"),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

af_gang_mail/models.py
"""Models."""

import logging
import random
from datetime import timedelta

from django import template, urls
from django.conf import settings
from django.contrib import auth
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMultiAlternatives
from django.db import models
from django.db.models import Q
from django.utils.timezone import now

from autoslug import AutoSlugField
from django_countries.fields import CountryField

logger = logging.getLogger(__name__)


class UserManager(auth.models.UserManager):
    """User manager."""

    def eligible_for_draw(self):
        return self.filter(emailaddress__verified=True, is_active=True).exclude(
            Q(first_name="") & Q(last_name="")
        )


class User(auth.models.AbstractUser):
    """User"""

    address_line_1 = models.TextField("Address line 1", blank=True, null=False)
    address_line_2 = models.TextField("Address line 2", blank=True, null=False)
    address_city = models.TextField("City", blank=True, null=False)
    address_state = models.TextField("State", blank=True, null=False)
    address_postcode = models.TextField("Postcode", blank=True, null=False)
    address_country = CountryField("Country", blank=True, null=False)
    exchanges = models.ManyToManyField(
        "Exchange", related_name="users", through="UserInExchange"
    )

    objects = UserManager()

    def __str__(self):
        """Full name or email address."""

        if self.get_full_name():
            return self.get_full_name()

        if self.email:
            return self.email

        return super().__str__()

    def get_address_parts(self):
        """Get the parts of the address."""

        address_parts = [
            self.address_line_1,
            self.address_line_2,
            self.address_city,
            self.address_state,
            self.address_postcode,
            self.address_country.name,
        ]
        return [part for part in address_parts if part]

    def get_full_address(self):
        return "\n".join(self.get_address_parts())

    def has_short_address(self):
        return len(self.get_address_parts()) < 3

    def has_verified_email_address(self):
        return self.emailaddress_set.filter(verified=True).exists()

    class Meta:
        permissions = [
            ("statto", "Can view statto"),
        ]


class ExchangeManager(models.Manager):
    """Exchange manager."""

    @staticmethod
    def get_upcoming_filter_kwargs():
        return {"drawn__gt": now() + timedelta(minutes=1)}

    def upcoming(self):
        return self.filter(**self.get_upcoming_filter_kwargs())

    def not_upcoming(self):
        return self.filter(drawn__lt=now())

    def scheduled_for_confirmation(self):
        return self.filter(confirmation__lt=now(), confirmation_started__isnull=True)

    def scheduled_for_confirmation_reminder(self):
        return self.filter(
            confirmation_reminder__lt=now(), confirmation_reminder_started__isnull=True
        )

    def scheduled_for_draw(self):
        return self.filter(drawn__lt=now(), draw_started__isnull=True)

    def scheduled_for_send_reminder(self):
        return self.filter(sent__lt=now(), send_reminder_started__isnull=True)

    def scheduled_for_receive_reminder(self):
        return self.filter(received__lt=now(), receive_reminder_started__isnull=True)

    def drawn_not_sent(self):
        return self.filter(drawn__lt=now(), sent__gt=now())

    def past(self):
        return self.filter(received__lt=now())


class Exchange(models.Model):
    """Exchange"""

    name = models.TextField(blank=False, null=False)
    slug = AutoSlugField(populate_from="name", unique=True)
    confirmation = models.DateTimeField(blank=False, null=True)
    confirmation_reminder = models.DateTimeField(blank=False, null=True)
    drawn = models.DateTimeField(blank=False, null=False)
    sent = models.DateTimeField(blank=False, null=False)
    received = models.DateTimeField(blank=False, null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    confirmation_started = models.DateTimeField(blank=True, null=True)
    confirmation_reminder_started = models.DateTimeField(blank=True, null=True)
    draw_started = models.DateTimeField(blank=True, null=True)
    send_reminder_started = models.DateTimeField(blank=True, null=True)
    receive_reminder_started = models.DateTimeField(blank=True, null=True)
    send_emails = models.BooleanField(default=False)

    objects = ExchangeManager()

    def __str__(self):
        return self.name

    def clean(self):
        if (
            not self.confirmation
            < self.confirmation_reminder
            < self.drawn
            < self.sent
            < self.received
        ):
            raise ValidationError("Exchange dates must be in order.")

        return super().clean()

    class Meta:
        ordering = ["drawn"]


class UserInExchange(models.Model):
    """User in exchange."""

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_in_exchanges"
    )
    exchange = models.ForeignKey(
        Exchange, on_delete=models.CASCADE, related_name="users_in_exchange"
    )
    confirmed = models.BooleanField(default=False, blank=False, null=False)

    def _as_email_message(
        self, subject_template, body_text_template, body_html_template, **kwargs
    ):
        """Construct an EmailMessage."""

        subject_template = template.loader.get_template(subject_template)
        body_text_template = template.loader.get_template(body_text_template)
        body_html_template = template.loader.get_template(body_html_template)

        site = Site.objects.get_current()
        scheme = "https" if settings.SECURE_SSL_REDIRECT else "http"
        context = {
            "user": self.user,
            "exchange": self.exchange,
            "site": site,
            "confirm_url": f"{ scheme }://{ site.domain }"
            + urls.reverse(
                "confirm_participation", kwargs={"slug": self.exchange.slug}
            ),
        }

        msg = EmailMultiAlternatives(
            subject=subject_template.render(context),
            body=body_text_template.render(context),
            from_email=settings.DEFAULT_FROM_EMAIL,
            to=[self.user.email],
            **kwargs,
        )
        msg.attach_alternative(body_html_template.render(context), "text/html")

        return msg

    def as_confirmation_email_message(self, **kwargs):
        return self._as_email_message(
            "af_gang_mail/confirmation-email-subject.txt",
            "af_gang_mail/confirmation-email-body.txt",
            "af_gang_mail/confirmation-email-body.html",
            **kwargs,
        )

    def as_confirmation_reminder_email_message(self, **kwargs):
        return self._as_email_message(
            "af_gang_mail/confirmation-reminder-email-subject.txt",
            "af_gang_mail/confirmation-reminder-email-body.txt",
            "af_gang_mail/confirmation-reminder-email-body.html",
            **kwargs,
        )


class DrawManager(models.Manager):
    """Draw manager."""

    def _user_pairs(self, users):  # pylint: disable=no-self-use
        for i in range(-1, len(users) - 1):
            yield (users[i], users[i + 1])

    def _draws(self, exchange, users):
        for sender, recipient in self._user_pairs(users):
            yield Draw(sender=sender, recipient=recipient, exchange=exchange)

    def _score_draws(self, draws):
        """
        Score a set of draws.

        The lower the score, the better.

        Zero is a perfect score.
        """

        # Count number of repeated sender/recipient pairs
        logger.info("Testing for %d repeated sender-recipient pairs.", len(draws))
        repeated_sender_recipient_pairs = 0
        for i, draw in enumerate(draws):
            if self.filter(
                sender_id=draw.sender_id, recipient_id=draw.recipient_id
            ).exists():
                repeated_sender_recipient_pairs = repeated_sender_recipient_pairs + 1

            if i % 1000 == 0 and i > 0:
                logger.info("Tested %d/%d sender-recipient pairs.", i, len(draws))

        logger.info(
            "Got %d repeated sender-recipient pairs.", repeated_sender_recipient_pairs
        )

        return repeated_sender_recipient_pairs

    def bulk_create_from_exchange(self, exchange, max_attempts=1000):
        """Create draws for an exchange."""

        logger.info("Preparing set of draws for %s.", exchange.name)

        confirmed_user_ids = exchange.users_in_exchange.filter(
            confirmed=True
        ).values_list("user_id", flat=True)
        users = list(
            exchange.users.eligible_for_draw().filter(id__in=confirmed_user_ids)
        )
        logger.info("%d users.", len(users))

        # Run through some iterations and try to generate a perfect result.
        iteration_results = []
        while len(iteration_results) < max_attempts:
            logger.info("Shuffling users.")
            random.shuffle(users)
            logger.info("Shuffled users.")

            logger.info("Generating draws.")
            draws = list(self._draws(exchange, users))
            logger.info("Generated draws.")

            logger.info("Scoring draws.")
            score = self._score_draws(draws)
            logger.info("Draws scored %d (higher is worse; zero is perfect).", score)
            if score == 0:
                logger.info("Got a perfect result!")
                break

            iteration_results.append((score, draws))

        if score > 0:
            logger.info("Didn't get a perfect result. Selecting the best result.")
            result = min(iteration_results, key=lambda result: result[0])
            logger.info(
                "Selected a result with score %d (higher is worse; zero is perfect).",

af_gang_mail/templates/af_gang_mail/manage_exchanges/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <form method="post">
    <h1>Create Exchange</h1>
    {% csrf_token %}
    {{ form|crispy }}
    <button>Create Exchange</button>
    <a class="button secondary" href="{% url 'manage-exchanges' %}">Back to List</a>
  </form>

{% endblock %}

af_gang_mail/templates/af_gang_mail/manage_exchanges/delete-draws-for-exchange.html
{% extends 'base.html' %}

{% block content %}

  <form method="post">
    <h1>Delete Draws for {{ object.name }}?</h1>
    {% csrf_token %}
    <button>Delete</button>
  </form>

{% endblock %}

af_gang_mail/templates/af_gang_mail/manage_exchanges/delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <form method="post">
    <h1>Delete {{ object.name }}?</h1>
    {% csrf_token %}
    {{ form|crispy }}
    <button>Delete</button>
  </form>

{% endblock %}

af_gang_mail/templates/af_gang_mail/manage_exchanges/draw.html
{% extends 'base.html' %}

{% block content %}

  <form method="post">
    <h1>Draw {{ object.name }}?</h1>
    {% csrf_token %}
    <button>Draw</button>
  </form>

{% endblock %}

af_gang_mail/templates/af_gang_mail/manage_exchanges/list.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}

{% block body_classes %}manage-exchanges{% endblock %}

{% block content %}

<div class="yellow-box">
  <h1>Manage Exchanges</h1>
  {% render_table table %}

  <nav>
     {% if perms.af_gang_mail.add_exchange %}
       <a href="{% url 'create-exchange' %}">Create</a>
     {% endif %}
   </nav>
</div>

{% endblock %}

af_gang_mail/templates/af_gang_mail/manage_exchanges/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <form method="post">
    <h1>Edit {{ exchange.name }}</h1>
    {% csrf_token %}
    {{ form|crispy }}
    <button>Save Changes to Exchange</button>
    <a class="button secondary" href="{% url 'view-exchange' slug=exchange.slug %}">Back to {{ exchange.name }}</a>
  </form>

{% endblock %}

af_gang_mail/templates/af_gang_mail/manage_exchanges/view-draw.html
{% extends 'base.html' %}

{% block content %}

<div class="yellow-box">
  <dl>

    {% for field, value in draw_data.items %}
      <dt>{{ field }}</dt>
      <dd>{{ value }}</dd>
    {% endfor %}

    <dt>Confirmation Email Subject</dt>
    <dd>{{ confirmation_email_message.subject }}</dd>
    <dt>Confirmation Email Body (Plain Text)</dt>
    <dd><pre>{{ confirmation_email_message.body }}</pre></dd>
    {% for email_body, mime_type in confirmation_email_message.alternatives %}
      <dt>Confirmation Email Body ({{ mime_type }})</dt>
      <dd>{{ email_body }}</dd>
    {% endfor %}

    <dt>Drawn Email Subject</dt>
    <dd>{{ draw_email_message.subject }}</dd>
    <dt>Drawn Email Body (Plain Text)</dt>
    <dd><pre>{{ draw_email_message.body }}</pre></dd>
    {% for email_body, mime_type in draw_email_message.alternatives %}
      <dt>Drawn Email Body ({{ mime_type }})</dt>
      <dd>{{ email_body }}</dd>
    {% endfor %}

    <dt>Send Reminder Email Subject</dt>
    <dd>{{ send_reminder_email_message.subject }}</dd>
    <dt>Send Reminder Email Body (Plain Text)</dt>
    <dd><pre>{{ send_reminder_email_message.body }}</pre></dd>
    {% for email_body, mime_type in send_reminder_email_message.alternatives %}
      <dt>Send Reminder Email Body ({{ mime_type }})</dt>
      <dd>{{ email_body }}</dd>
    {% endfor %}

    <dt>Receive Reminder Email Subject</dt>
    <dd>{{ receive_reminder_email_message.subject }}</dd>
    <dt>Receive Reminder Email Body (Plain Text)</dt>
    <dd><pre>{{ receive_reminder_email_message.body }}</pre></dd>
    {% for email_body, mime_type in receive_reminder_email_message.alternatives %}
      <dt>Receive Reminder Email Body ({{ mime_type }})</dt>
      <dd>{{ email_body }}</dd>
    {% endfor %}

  </dl>

  <nav>
    <a href="{% url 'view-exchange' slug=draw.exchange.slug %}">Back to {{ draw.exchange }}</a>
  </nav>
</div>

{% endblock %}

af_gang_mail/templates/af_gang_mail/manage_exchanges/view.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}

{% block content %}

<div class="yellow-box">
  <h1>{{ exchange.name }}</h1>

  <dl>
    {% for field, value in exchange_data.items %}
      <dt>{{ field }}</dt>
      <dd>{{ value }}</dd>
    {% endfor %}
    <dt>Users</dt>
    <dd>
      {% render_table user_table %}
    </dd>
    <dt>Draws</dt>
    <dd>
      {% render_table draw_table %}
    </dd>
  </dl>

  <nav>
    <a href="{% url 'manage-exchanges' %}">Back to List</a>
    {% if perms.af_gang_mail.change_exchange %}
      <a href="{% url 'update-exchange' slug=exchange.slug %}">Edit</a>
    {% endif %}
    {% if perms.af_gang_mail.delete_exchange %}
      <a href="{% url 'delete-exchange' slug=exchange.slug %}">Delete</a>
    {% endif %}
    {% if perms.af_gang_mail.add_draw %}
      <a href="{% url 'draw-exchange' slug=exchange.slug %}">Draw</a>
    {% endif %}
    {% if perms.af_gang_mail.delete_draw %}
      <a href="{% url 'delete-draws-for-exchange' slug=exchange.slug %}">Delete Draws for Exchange</a>
    {% endif %}
  </nav>
</div>

{% endblock %}